# Generated by Django 3.1.6 on 2021-02-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videoinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('pub_date', models.DateField(verbose_name='動画投稿時間')),
                ('image', models.ImageField(upload_to='arikui/images/')),
            ],
        ),
    ]
